## Numpy
#### python objects:
    1. high-level number objects: integers. floating point
    2. containers: lists (costless insertion and append), dictionaries (fast look up)

#### Numpy provides:
    1. extension package to Python for multi-dimensional arrays.
    2. closer to hardware (efficiency)
    3. designed for scienfic computation (convenience)
    4. Also known as array opriented computing.

In [3]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

[0 1 2 3]


In [2]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


#### Why is it useful : Memory-efficient container that provides fast numerical operation

In [1]:
# python lists
L = range(1000)
%timeit [i**2 for i in L]

306 µs ± 21.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [4]:
a = np.arange(1000)
%timeit a**2

1.38 µs ± 70.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## 1. Creating arrays

#### 1.1. Manual Construction of arrays

In [5]:
# 1- D

a = np.array([0, 1, 2, 3])

a

array([0, 1, 2, 3])

In [6]:
# print dimensions

a.ndim

1

In [7]:
# shape
a.shape

(4,)

In [8]:
# 2-D Arrays

b = np.array([[0, 1, 2], [3, 4, 5]])

In [9]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
b.ndim

2

In [11]:
b.shape

(2, 3)

In [12]:
len(b)

2

In [14]:
# 3-D Arrays
c = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])

c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
c.ndim

3

In [16]:
c.shape

(2, 2, 2)

1D Array -> Vector<br>
2D Array -> Matrix<br>
3D Array -> Tensor<br>

### 1.2 Functions for creating array

In [17]:
# using arrange function

a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b = np.arange(1, 10, 2)
b

array([1, 3, 5, 7, 9])

In [21]:
# using linspace (linear space)

a = np.linspace(0, 1, 6) # start, end, number of points

a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [22]:
# common arrays

a = np.ones((3, 3))

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
b = np.zeros((3, 3))

b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c = np.eye(3)  # Retur
